# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calendary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calendary
  pod 'FSCalendar'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'


  target 'CalendaryTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'CalendaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
